export const books = [
    {
      id: 1,
      title: "The Midnight Library",
      authors: ["Matt Haig"],
      cover: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?q=80&w=400&auto=format&fit=crop",
      status: "Available",
      publishedDate: "2020-08-13",
      description: "Between life and death there is a library, and within that library, the shelves go on forever. Every book provides a chance to try another life you could have lived.",
      isbn: "978-0525559474",
      pages: 304,
      language: "English",
      genre: ["Fiction", "Fantasy", "Contemporary"],
    },
    {
      id: 2,
      title: "Good Omens",
      authors: ["Terry Pratchett", "Neil Gaiman"],
      cover: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?q=80&w=400&auto=format&fit=crop",
      status: "Available",
      publishedDate: "1990-05-01",
      description: "According to The Nice and Accurate Prophecies of Agnes Nutter, Witch, the world will end on a Saturday. Next Saturday, in fact. Just before dinner.",
      isbn: "978-0060853976",
      pages: 288,
      language: "English",
      genre: ["Fiction", "Fantasy", "Humor"],
    },
    {
      id: 3,
      title: "Project Hail Mary",
      authors: ["Andy Weir"],
      cover: "https://images.unsplash.com/photo-1532012197267-da84d127e765?q=80&w=400&auto=format&fit=crop",
      status: "On Loan",
      publishedDate: "2021-05-04",
      description: "Ryland Grace is the sole survivor on a desperate, last-chance mission—and if he fails, humanity and the Earth itself will perish.",
      isbn: "978-0593135204",
      pages: 496,
      language: "English",
      genre: ["Science Fiction", "Space Opera"],
    },
  ]